"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-19 16:22:11.599247

"""

from pathlib import Path
from typing import Sequence, Union

import pgvector.sqlalchemy
import psycopg
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector backs the embedding columns; pgcrypto backs gen_random_uuid().
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_codes_email"), "auth_codes", ["email"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("r2_bucket_name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "vaults",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("r2_bucket_name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compile_cache_entries",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("phase", sa.Text(), nullable=False),
        sa.Column("cache_key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vault_id", "phase", "cache_key"),
    )
    op.create_index(
        op.f("ix_compile_cache_entries_vault_id"),
        "compile_cache_entries",
        ["vault_id"],
        unique=False,
    )
    op.create_table(
        "llm_cost_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("vault_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("current_phase", sa.Text(), nullable=False),
        sa.Column("phase_status", sa.Text(), nullable=False),
        sa.Column(
            "progress_steps",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("ingest_task_id", sa.UUID(), nullable=True),
        sa.Column("compile_intent_id", sa.UUID(), nullable=True),
        sa.Column("compile_task_id", sa.UUID(), nullable=True),
        sa.Column("active_task_id", sa.UUID(), nullable=True),
        sa.Column("active_task_type", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_vault_id"), "pipeline_runs", ["vault_id"], unique=False
    )
    op.create_table(
        "search_index",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("heading", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("tsv", postgresql.TSVECTOR(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(1024), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vault_id", "path", "chunk_index"),
    )
    op.create_index(
        op.f("ix_search_index_vault_id"), "search_index", ["vault_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("origin", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "vault_id"),
    )
    op.create_index(
        op.f("ix_sessions_updated_at"), "sessions", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_sessions_vault_id"), "sessions", ["vault_id"], unique=False
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.Text(), nullable=False),
        sa.Column("client_hash", sa.Text(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=True),
        sa.Column("provenance_session_id", sa.UUID(), nullable=True),
        sa.Column("provenance_exchange_id", sa.Text(), nullable=True),
        sa.Column("provenance_session_query", sa.Text(), nullable=True),
        sa.Column("provenance_source_doc_path", sa.Text(), nullable=True),
        sa.Column("provenance_source_anchor", sa.Text(), nullable=True),
        sa.Column("provenance_source_paragraph_index", sa.Integer(), nullable=True),
        sa.Column("provenance_anchored_to", sa.Text(), nullable=True),
        sa.Column("provenance_anchored_section", sa.Text(), nullable=True),
        sa.Column("provenance_intent", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("precis", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("published_date", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("ARRAY[]::text[]"),
            nullable=False,
        ),
        sa.Column(
            "derived_extras",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vault_id", "file_path"),
    )
    op.create_index(
        "ix_source_documents_vault_client_hash",
        "source_documents",
        ["vault_id", "client_hash"],
        unique=False,
        postgresql_where=sa.text("client_hash IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_source_documents_vault_id"),
        "source_documents",
        ["vault_id"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "article_status", sa.Text(), server_default="no_article", nullable=False
        ),
        sa.Column("compiled_from_hash", sa.Text(), nullable=True),
        sa.Column("rendered_from_hash", sa.Text(), nullable=True),
        sa.Column("supersedes", sa.UUID(), nullable=True),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id"),
        sa.UniqueConstraint("vault_id", "slug"),
    )
    op.create_index(op.f("ix_topics_vault_id"), "topics", ["vault_id"], unique=False)
    op.create_table(
        "vault_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "EDITOR", "VIEWER", name="member_role"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vault_id", "user_id"),
    )
    op.create_table(
        "compile_intents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_task_id", sa.UUID(), nullable=True),
        sa.Column("satisfied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"], ["pipeline_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_compile_intents_one_pending",
        "compile_intents",
        ["vault_id"],
        unique=True,
        postgresql_where=sa.text("dispatched_at IS NULL"),
    )
    op.create_index(
        "ix_compile_intents_pending",
        "compile_intents",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("dispatched_at IS NULL"),
    )
    op.create_index(
        op.f("ix_compile_intents_pipeline_run_id"),
        "compile_intents",
        ["pipeline_run_id"],
        unique=False,
    )
    op.create_table(
        "ideas",
        sa.Column("idea_id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["source_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("idea_id"),
    )
    op.create_index(
        op.f("ix_ideas_document_id"), "ideas", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_ideas_vault_id"), "ideas", ["vault_id"], unique=False)
    op.create_table(
        "source_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="proposal_status"),
            nullable=False,
        ),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("dest_path", sa.Text(), server_default="", nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_proposals_document_id"),
        "source_proposals",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_proposals_vault_id"),
        "source_proposals",
        ["vault_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pipeline_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"], ["pipeline_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_pipeline_run_id"), "tasks", ["pipeline_run_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_vault_id"), "tasks", ["vault_id"], unique=False)
    op.create_table(
        "topic_links",
        sa.Column("source_topic_id", sa.UUID(), nullable=False),
        sa.Column("target_topic_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_topic_id"], ["topics.topic_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_topic_id"], ["topics.topic_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("source_topic_id", "target_topic_id"),
    )
    op.create_table(
        "topic_membership",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("idea_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.topic_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "idea_id"),
    )
    op.create_table(
        "topic_related",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("related_topic_id", sa.UUID(), nullable=False),
        sa.Column("shared_ideas", sa.Integer(), nullable=False),
        sa.Column("jaccard", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_topic_id"], ["topics.topic_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.topic_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "related_topic_id"),
    )
    op.create_table(
        "wiki_articles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("precis", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.topic_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vault_id", "topic_id"),
    )
    op.create_index(
        op.f("ix_wiki_articles_vault_id"), "wiki_articles", ["vault_id"], unique=False
    )
    op.create_table(
        "anchors",
        sa.Column("idea_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["idea_id"], ["ideas.idea_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("idea_id", "position"),
    )
    op.create_table(
        "backlinks",
        sa.Column("source_article_id", sa.UUID(), nullable=False),
        sa.Column("target_article_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_article_id"], ["wiki_articles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_article_id"], ["wiki_articles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("source_article_id", "target_article_id"),
    )
    # ### end Alembic commands ###

    # --- Specialized search_index indexes (not expressible via the ORM) ---
    # Full-text (BM25) over the tsvector and ANN over the embedding. Both
    # are queried by SearchRepository (tsquery + cosine_distance).
    op.execute("CREATE INDEX ix_search_index_tsv ON search_index USING GIN (tsv)")
    op.execute(
        "CREATE INDEX ix_search_index_embedding ON search_index "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # --- Pipeline progress LISTEN/NOTIFY ---
    # The DB row is the durable source of truth; this trigger emits a tiny
    # "go re-read this run" wakeup so SSE handlers don't poll. Insert fires
    # always; update fires only on a meaningful column change.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION notify_pipeline_run_changed()
        RETURNS trigger AS $$
        BEGIN
            PERFORM pg_notify(
                'pipeline_progress',
                json_build_object(
                    'pipeline_run_id', NEW.id,
                    'vault_id', NEW.vault_id
                )::text
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER pipeline_runs_notify_insert
        AFTER INSERT ON pipeline_runs
        FOR EACH ROW
        EXECUTE FUNCTION notify_pipeline_run_changed();
        """
    )
    op.execute(
        """
        CREATE TRIGGER pipeline_runs_notify_update
        AFTER UPDATE ON pipeline_runs
        FOR EACH ROW
        WHEN (
            OLD.status IS DISTINCT FROM NEW.status
            OR OLD.current_phase IS DISTINCT FROM NEW.current_phase
            OR OLD.phase_status IS DISTINCT FROM NEW.phase_status
            OR OLD.progress_steps IS DISTINCT FROM NEW.progress_steps
            OR OLD.error IS DISTINCT FROM NEW.error
            OR OLD.completed_at IS DISTINCT FROM NEW.completed_at
        )
        EXECUTE FUNCTION notify_pipeline_run_changed();
        """
    )

    # --- Absurd durable task queue schema ---
    # absurd.sql is a multi-statement script; asyncpg's extended query
    # protocol can't run it in one call, so load it over a side psycopg
    # connection (simple query protocol). Runs once on the fresh DB.
    url = op.get_bind().engine.url
    pg_url = (
        f"postgresql://{url.username or ''}"
        f"{':%s' % url.password if url.password else ''}"
        f"@{url.host or 'localhost'}:{url.port or 5432}/{url.database}"
    )
    sql = (Path(__file__).resolve().parent.parent / "absurd.sql").read_text()
    with psycopg.connect(pg_url, autocommit=True) as conn:
        conn.execute(sql.encode())
        conn.execute(b"SELECT absurd.create_queue('default')")


def downgrade() -> None:
    """Initial migration — nothing to undo. Drop the schema directly if
    you really need a clean slate."""
    raise NotImplementedError(
        "downgrade past initial schema is not supported; drop the schema instead"
    )
