"""auth codes keyed by email not user id

Revision ID: bbd7c8738bc0
Revises: 0016831828fa
Create Date: 2026-04-05 17:58:19.316914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd7c8738bc0'
down_revision: Union[str, Sequence[str], None] = '0016831828fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_codes', sa.Column('email', sa.String(length=320), nullable=False))
    op.create_index(op.f('ix_auth_codes_email'), 'auth_codes', ['email'], unique=False)
    op.drop_constraint(op.f('auth_codes_user_id_fkey'), 'auth_codes', type_='foreignkey')
    op.drop_column('auth_codes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_codes', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('auth_codes_user_id_fkey'), 'auth_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_codes_email'), table_name='auth_codes')
    op.drop_column('auth_codes', 'email')
    # ### end Alembic commands ###
