"""drop brain slug unique constraint and index

Revision ID: c8658f05c8dc
Revises: bf89776aff8d
Create Date: 2026-04-05 15:02:09.284425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8658f05c8dc'
down_revision: Union[str, Sequence[str], None] = 'bf89776aff8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brains_slug'), table_name='brains')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brains_slug'), 'brains', ['slug'], unique=True)
    # ### end Alembic commands ###
